name: Naturaldisater
version: '${project.version}'
main: me.naturaldisater.Naturaldisater
authors: [ KIM ]
description: Natural Disater
commands:
  fire:
    description: Axit
    usage: /fire
    permission: Natural.fire
    permission-message: U don't have permission
  axit:
    description: Axit
    usage: /axit
    permission: Natural.axit
    permission-message: U don't have permission
  wither:
    description: Wither
    usage: /wither
    permission: Natural.wither
    permission-message: U don't have permission
  ghast:
    description: Ghast
    usage: /ghast
    permission: Natural.ghast
    permission-message: U don't have permisson
permissions:
  Natural.fire:
    default: op
  Natural.axit:
    default: op
  Natural.wither:
    default: op